[tool.ruff.lint]
# Only show real issues, not style preferences
select = [
    # Security issues
    "S106", "S105", "S301", "S310", "S603", "S605", "S311",
    # Logic bugs
    "E722", "B017", "F811", "B904", "RUF006",
    # Performance issues
    "RUF006",
    # Critical naming issues that cause bugs
    "E741",  # Ambiguous variable name
    "B020",  # Loop variable overrides iterator
    "PLR1704",  # Redefined argument from local
    "PLW2901",  # Redefined loop name
]

# Ignore style-only rules
ignore = [
    # Style preferences
    "PLR2004",  # Magic value comparisons
    "D205",     # Missing blank line after summary
    "Q000",     # Bad quotes in inline string
    "W293",     # Blank line with whitespace
    "W291",     # Trailing whitespace
    "D212",     # Multi-line summary first line
    "D415",     # Missing terminal punctuation
    "PLC0415",  # Import outside top-level
    "E402",     # Module import not at top
    "F401",     # Unused imports
    "N806",     # Non-lowercase variable in function
    "N803",     # Invalid argument name
    "N801",     # Invalid class name
    "N802",     # Invalid function name
    "PLR0911",  # Too many return statements
    "SIM102",   # Collapsible if
    "SIM108",   # If-else block instead of if-exp
    "SIM117",   # Multiple with statements
    "SIM103",   # Needless bool
    "UP006",    # Non-pep585-annotation
    "UP035",    # Deprecated import
    "UP015",    # Redundant open modes
    "F541",     # F-string missing placeholders
    "RUF001",   # Ambiguous unicode character string
    "RUF059",   # Unused unpacked variable
    "S608",     # Hardcoded SQL expression
    "S108",     # Hardcoded temp file
    "S113",     # Request without timeout
    "S602",     # Subprocess popen with shell equals true
    "SIM115",   # Open file with context handler
    "D106",     # Undocumented public nested class
    "D417",     # Undocumented param
    "PLE0118",  # Load before global declaration
    "PLW0603",  # Global statement
    "S103",     # Bad file permissions
    "S110",     # Try-except-pass
    "S112",     # Try-except-continue
    "B007",     # Unused loop control variable
    "B018",     # Useless expression
    "RUF012",   # Mutable class default
    "ARG001",   # Unused function argument
    "ARG002",   # Unused method argument
]

[tool.ruff]
# Line length
line-length = 100

# Target Python version
target-version = "py311"