# Generated by Django 5.2.6 on 2025-12-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0004_add_risk_assessment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='riskassessment',
            new_name='auth0login__user_id_31ff96_idx',
            old_name='auth0login__user_id_f1a2b3_idx',
        ),
        migrations.RenameIndex(
            model_name='riskassessment',
            new_name='auth0login__user_id_cc941e_idx',
            old_name='auth0login__user_id_c4d5e6_idx',
        ),
        migrations.RenameIndex(
            model_name='tradinggate',
            new_name='auth0login__user_id_a20835_idx',
            old_name='auth0login__user_id_7c4d0a_idx',
        ),
        migrations.RenameIndex(
            model_name='tradinggate',
            new_name='auth0login__live_tr_611821_idx',
            old_name='auth0login__live_tr_a3e5f9_idx',
        ),
    ]
