# Generated by Django 4.2.27 on 2026-02-06 07:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "auth0login",
            "0005_rename_auth0login__user_id_f1a2b3_idx_auth0login__user_id_31ff96_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 6, 7, 50, 3, 594823, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credential",
            name="is_valid",
            field=models.BooleanField(
                default=False, help_text="Whether credentials have been validated"
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="key_version",
            field=models.IntegerField(
                default=1, help_text="Encryption key version for rotation"
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="last_rotated_at",
            field=models.DateTimeField(
                blank=True, help_text="When credentials were last rotated", null=True
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="last_validated_at",
            field=models.DateTimeField(
                blank=True, help_text="When credentials were last validated", null=True
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="validation_error",
            field=models.TextField(
                blank=True, default="", help_text="Last validation error message if any"
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="alpaca_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Encrypted Alpaca API key",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="alpaca_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Encrypted Alpaca secret key",
                max_length=500,
            ),
        ),
        migrations.CreateModel(
            name="WizardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trading_mode",
                    models.CharField(
                        choices=[("paper", "Paper Trading"), ("live", "Live Trading")],
                        default="paper",
                        help_text="Paper or live trading mode",
                        max_length=10,
                    ),
                ),
                (
                    "selected_strategies",
                    models.JSONField(
                        default=list, help_text="List of strategy IDs selected by user"
                    ),
                ),
                (
                    "risk_profile",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("moderate", "Moderate"),
                            ("aggressive", "Aggressive"),
                        ],
                        default="moderate",
                        help_text="User's risk profile",
                        max_length=20,
                    ),
                ),
                (
                    "max_position_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        help_text="Maximum position size percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "max_daily_loss_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Maximum daily loss percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "max_positions",
                    models.IntegerField(
                        default=10, help_text="Maximum number of open positions"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this configuration is currently active",
                    ),
                ),
                (
                    "broker_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether broker connection has been validated",
                    ),
                ),
                (
                    "broker_validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When broker connection was last validated",
                        null=True,
                    ),
                ),
                (
                    "email_confirmation_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether setup confirmation email was sent",
                    ),
                ),
                (
                    "email_confirmation_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When confirmation email was sent",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated risk assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wizard_configs",
                        to="auth0login.riskassessment",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizard_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wizard Configuration",
                "verbose_name_plural": "Wizard Configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique session identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1, help_text="Current wizard step (1-5)"
                    ),
                ),
                (
                    "steps_completed",
                    models.JSONField(
                        default=list, help_text="List of completed step numbers"
                    ),
                ),
                (
                    "step_data",
                    models.JSONField(
                        default=dict,
                        help_text="Data collected at each step (for resume)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                            ("skipped", "Skipped"),
                        ],
                        default="in_progress",
                        help_text="Current session status",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the session started"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity timestamp"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session was completed",
                        null=True,
                    ),
                ),
                (
                    "step_timings",
                    models.JSONField(
                        default=dict, help_text="Time spent on each step in seconds"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Browser user agent", max_length=500
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this session belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wizard_configuration",
                    models.OneToOneField(
                        blank=True,
                        help_text="Final configuration created from this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_session",
                        to="auth0login.wizardconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Session",
                "verbose_name_plural": "Onboarding Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wizardconfiguration",
            index=models.Index(
                fields=["user", "is_active"], name="auth0login__user_id_9af8d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wizardconfiguration",
            index=models.Index(
                fields=["created_at"], name="auth0login__created_193e7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsession",
            index=models.Index(
                fields=["user", "status"], name="auth0login__user_id_267c3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsession",
            index=models.Index(
                fields=["session_id"], name="auth0login__session_e99eb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsession",
            index=models.Index(
                fields=["status", "started_at"], name="auth0login__status_0de515_idx"
            ),
        ),
    ]
