# Generated by Django 4.2.27 on 2026-02-21 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth0login", "0008_add_audit_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="auth0login__user_id_c6ae1b_idx",
            old_name="auth0login_audit_user_ts",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="auth0login__event_t_1d588c_idx",
            old_name="auth0login_audit_type_ts",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="auth0login__severit_f16e53_idx",
            old_name="auth0login_audit_sev_ts",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="auth0login__target__e420e4_idx",
            old_name="auth0login_audit_target_ts",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of target object (e.g. 'ml_model', 'circuit_breaker')",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User being acted upon (e.g. role assigned TO this user)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_target_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
