"""Options pricing and analysis module."""

from .pricing_engine import (
    BlackScholesEngine,
    Greeks,
    OptionsContract,
    RealOptionsPricingEngine,
    create_options_pricing_engine,
)
from .smart_selection import (
    LiquidityRating,
    OptionsAnalysis,
    SelectionCriteria,
    SmartOptionsSelector,
    create_smart_options_selector,
)
from .assignment_risk import (
    OptionContract,
    UnderlyingState,
    auto_exercise_likely,
    early_assignment_risk,
    pin_risk,
)
from .exotic_spreads import (
    SpreadType,
    SpreadDirection,
    LegType,
    SpreadLeg,
    SpreadGreeks,
    OptionSpread,
    IronCondor,
    IronButterfly,
    Butterfly,
    BrokenWingButterfly,
    CalendarSpread,
    DiagonalSpread,
    Straddle,
    Strangle,
    RatioSpread,
    SpreadAnalysis,
)
from .spread_builder import (
    SpreadBuilder,
    SpreadBuilderConfig,
    create_spread_builder,
)
from .spread_executor import (
    SpreadExecutor,
    SpreadOrder,
    LegOrder,
    OrderStatus,
    ExecutionStrategy,
    ExecutionResult,
)
from .advanced_spreads import (
    AdvancedSpreadType,
    BoxSpread,
    JadeLizard,
    PoorMansCoveredCall,
    Collar,
    ProtectivePut,
    ChristmasTree,
    DoubleDiagonal,
    Zebra,
    BrokenWingCondor,
    SyntheticLong,
    SyntheticShort,
    SpreadRollType,
    RollRecommendation,
    SpreadAdjustmentEngine,
    SpreadScanner,
)
from .portfolio_greeks import (
    OptionPosition,
    StockPosition,
    UnderlyingGreeks,
    PortfolioGreeks,
    PortfolioGreeksCalculator,
    GreeksMonitor,
    RiskMetric,
)
from .payoff_visualizer import (
    PayoffDiagramConfig,
    PayoffDiagramGenerator,
    GreeksDashboard,
    generate_pnl_heatmap,
)

__all__ = [
    # Advanced Spreads
    "AdvancedSpreadType",
    # Pricing
    "BlackScholesEngine",
    "BoxSpread",
    "BrokenWingButterfly",
    "BrokenWingCondor",
    "Butterfly",
    "CalendarSpread",
    "ChristmasTree",
    "Collar",
    "DiagonalSpread",
    "DoubleDiagonal",
    "ExecutionResult",
    "ExecutionStrategy",
    "Greeks",
    "GreeksDashboard",
    "GreeksMonitor",
    "IronButterfly",
    "IronCondor",
    "JadeLizard",
    "LegOrder",
    "LegType",
    # Selection
    "LiquidityRating",
    # Assignment Risk
    "OptionContract",
    # Portfolio Greeks
    "OptionPosition",
    "OptionSpread",
    "OptionsAnalysis",
    "OptionsContract",
    "OrderStatus",
    # Payoff Visualization
    "PayoffDiagramConfig",
    "PayoffDiagramGenerator",
    "PoorMansCoveredCall",
    "PortfolioGreeks",
    "PortfolioGreeksCalculator",
    "ProtectivePut",
    "RatioSpread",
    "RealOptionsPricingEngine",
    "RiskMetric",
    "RollRecommendation",
    "SelectionCriteria",
    "SmartOptionsSelector",
    "SpreadAdjustmentEngine",
    "SpreadAnalysis",
    # Spread Builder
    "SpreadBuilder",
    "SpreadBuilderConfig",
    "SpreadDirection",
    # Spread Executor
    "SpreadExecutor",
    "SpreadGreeks",
    "SpreadLeg",
    "SpreadOrder",
    "SpreadRollType",
    "SpreadScanner",
    # Exotic Spreads
    "SpreadType",
    "StockPosition",
    "Straddle",
    "Strangle",
    "SyntheticLong",
    "SyntheticShort",
    "UnderlyingGreeks",
    "UnderlyingState",
    "Zebra",
    "auto_exercise_likely",
    "create_options_pricing_engine",
    "create_smart_options_selector",
    "create_spread_builder",
    "early_assignment_risk",
    "generate_pnl_heatmap",
    "pin_risk",
]
