# Generated by Django 4.2.27 on 2026-02-06 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tradingbot", "0011_remove_company_news_remove_price_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this backtest run",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="User-defined name for this run",
                        max_length=200,
                    ),
                ),
                (
                    "strategy_name",
                    models.CharField(
                        db_index=True,
                        help_text="Strategy that was backtested",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField(help_text="Backtest start date")),
                ("end_date", models.DateField(help_text="Backtest end date")),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Starting capital for backtest",
                        max_digits=15,
                    ),
                ),
                (
                    "benchmark",
                    models.CharField(
                        default="SPY",
                        help_text="Benchmark symbol for comparison",
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Strategy parameters used in this run"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the backtest",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if backtest failed"
                    ),
                ),
                (
                    "total_return_pct",
                    models.FloatField(help_text="Total return percentage", null=True),
                ),
                (
                    "benchmark_return_pct",
                    models.FloatField(
                        help_text="Benchmark return percentage", null=True
                    ),
                ),
                ("alpha", models.FloatField(help_text="Alpha vs benchmark", null=True)),
                ("beta", models.FloatField(help_text="Beta vs benchmark", null=True)),
                (
                    "sharpe_ratio",
                    models.FloatField(help_text="Sharpe ratio", null=True),
                ),
                (
                    "sortino_ratio",
                    models.FloatField(help_text="Sortino ratio", null=True),
                ),
                (
                    "calmar_ratio",
                    models.FloatField(help_text="Calmar ratio", null=True),
                ),
                (
                    "max_drawdown_pct",
                    models.FloatField(
                        help_text="Maximum drawdown percentage", null=True
                    ),
                ),
                (
                    "win_rate",
                    models.FloatField(help_text="Win rate percentage", null=True),
                ),
                (
                    "profit_factor",
                    models.FloatField(help_text="Profit factor", null=True),
                ),
                (
                    "total_trades",
                    models.IntegerField(help_text="Total number of trades", null=True),
                ),
                (
                    "winning_trades",
                    models.IntegerField(
                        help_text="Number of winning trades", null=True
                    ),
                ),
                (
                    "losing_trades",
                    models.IntegerField(help_text="Number of losing trades", null=True),
                ),
                (
                    "avg_win",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average winning trade",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "avg_loss",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average losing trade",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "avg_hold_days",
                    models.FloatField(
                        help_text="Average holding period in days", null=True
                    ),
                ),
                (
                    "final_equity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final portfolio value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total profit/loss",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "monthly_returns",
                    models.JSONField(
                        default=dict, help_text="Monthly returns {YYYY-MM: return_pct}"
                    ),
                ),
                (
                    "equity_curve",
                    models.JSONField(
                        default=list,
                        help_text="Daily equity snapshots [{date, equity, benchmark}]",
                    ),
                ),
                (
                    "drawdown_curve",
                    models.JSONField(
                        default=list,
                        help_text="Daily drawdown values [{date, drawdown_pct}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.JSONField(default=list, help_text="Tags for filtering"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="User marked as favorite"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="User notes about this run"),
                ),
                (
                    "custom_strategy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Custom strategy if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backtest_runs",
                        to="tradingbot.customstrategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who ran this backtest",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backtest Run",
                "verbose_name_plural": "Backtest Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("lstm", "LSTM - Sequence Prediction"),
                            ("cnn", "CNN - Pattern Recognition"),
                            ("transformer", "Transformer - Attention Model"),
                            ("hmm", "HMM - Regime Detection"),
                            ("xgboost", "XGBoost - Gradient Boosting"),
                            ("random_forest", "Random Forest"),
                        ],
                        default="lstm",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("active", "Active"),
                            ("training", "Training"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "symbols",
                    models.CharField(
                        help_text="Comma-separated symbols", max_length=500
                    ),
                ),
                (
                    "prediction_target",
                    models.CharField(
                        choices=[
                            ("direction", "Price Direction"),
                            ("returns", "Returns"),
                            ("volatility", "Volatility"),
                            ("regime", "Market Regime"),
                        ],
                        default="direction",
                        max_length=20,
                    ),
                ),
                (
                    "lookback_period",
                    models.IntegerField(
                        default=60, help_text="Days of historical data"
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(default=dict, help_text="Model hyperparameters"),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("predictions_count", models.IntegerField(default=0)),
                ("accuracy_history", models.JSONField(default=list)),
                ("loss_history", models.JSONField(default=list)),
                ("validation_history", models.JSONField(default=list)),
                (
                    "model_path",
                    models.CharField(
                        blank=True, help_text="Path to saved model file", max_length=500
                    ),
                ),
                ("model_version", models.IntegerField(default=1)),
                (
                    "features_config",
                    models.JSONField(
                        default=dict, help_text="Feature engineering config"
                    ),
                ),
                (
                    "feature_importance",
                    models.JSONField(
                        default=dict, help_text="Feature importance scores"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_trained", models.DateTimeField(blank=True, null=True)),
                ("last_prediction", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="RLAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("ppo", "PPO - Proximal Policy Optimization"),
                            ("ddpg", "DDPG - Deep Deterministic Policy Gradient"),
                            ("a2c", "A2C - Advantage Actor-Critic"),
                            ("sac", "SAC - Soft Actor-Critic"),
                            ("td3", "TD3 - Twin Delayed DDPG"),
                        ],
                        default="ppo",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("active", "Active"),
                            ("training", "Training"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "symbols",
                    models.CharField(
                        default="SPY", help_text="Trading symbols", max_length=500
                    ),
                ),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2, default=100000, max_digits=15
                    ),
                ),
                (
                    "max_position_size",
                    models.FloatField(
                        default=1.0, help_text="Max position as fraction of portfolio"
                    ),
                ),
                (
                    "transaction_cost",
                    models.FloatField(
                        default=0.001, help_text="Transaction cost as fraction"
                    ),
                ),
                ("hyperparameters", models.JSONField(default=dict)),
                ("total_episodes", models.IntegerField(default=0)),
                ("total_timesteps", models.IntegerField(default=0)),
                ("avg_reward", models.FloatField(blank=True, null=True)),
                ("sharpe_ratio", models.FloatField(blank=True, null=True)),
                ("sortino_ratio", models.FloatField(blank=True, null=True)),
                ("max_drawdown", models.FloatField(blank=True, null=True)),
                ("win_rate", models.FloatField(blank=True, null=True)),
                ("avg_return", models.FloatField(blank=True, null=True)),
                ("total_return", models.FloatField(blank=True, null=True)),
                ("reward_history", models.JSONField(default=list)),
                ("returns_history", models.JSONField(default=list)),
                ("episode_lengths", models.JSONField(default=list)),
                ("actor_path", models.CharField(blank=True, max_length=500)),
                ("critic_path", models.CharField(blank=True, max_length=500)),
                ("model_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_trained", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rl_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="SignalProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("flat", "Flat Fee"),
                            ("performance", "Performance Fee"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("subscribers_count", models.PositiveIntegerField(default=0)),
                ("max_subscribers", models.PositiveIntegerField(default=100)),
                (
                    "min_risk_tolerance",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum risk tolerance (1-5) required to follow",
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("total_signals_sent", models.PositiveIntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_return_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-subscribers_count"],
                "unique_together": {("owner", "strategy_name")},
            },
        ),
        migrations.CreateModel(
            name="WalkForwardRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("strategy_name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "train_window_days",
                    models.IntegerField(
                        default=90, help_text="Training window in days"
                    ),
                ),
                (
                    "test_window_days",
                    models.IntegerField(
                        default=30, help_text="Out-of-sample test window in days"
                    ),
                ),
                (
                    "step_days",
                    models.IntegerField(
                        default=30, help_text="Step size between windows"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Fixed parameters for testing"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                (
                    "total_windows",
                    models.IntegerField(
                        default=0, help_text="Total number of walk-forward windows"
                    ),
                ),
                ("windows_completed", models.IntegerField(default=0)),
                (
                    "avg_is_return",
                    models.FloatField(help_text="Average in-sample return", null=True),
                ),
                (
                    "avg_oos_return",
                    models.FloatField(
                        help_text="Average out-of-sample return", null=True
                    ),
                ),
                (
                    "avg_is_sharpe",
                    models.FloatField(help_text="Average in-sample Sharpe", null=True),
                ),
                (
                    "avg_oos_sharpe",
                    models.FloatField(
                        help_text="Average out-of-sample Sharpe", null=True
                    ),
                ),
                (
                    "robustness_ratio",
                    models.FloatField(help_text="OOS/IS performance ratio", null=True),
                ),
                (
                    "stability_score",
                    models.FloatField(
                        help_text="Performance stability across windows", null=True
                    ),
                ),
                (
                    "window_results",
                    models.JSONField(
                        default=list, help_text="Results for each walk-forward window"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Recommendations based on analysis"
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        default=list, help_text="Warnings about strategy robustness"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "custom_strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="walkforward_runs",
                        to="tradingbot.customstrategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walkforward_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Walk-Forward Run",
                "verbose_name_plural": "Walk-Forward Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=100, unique=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("ml_model", "ML Model Training"),
                            ("rl_agent", "RL Agent Training"),
                            ("optimization", "Hyperparameter Optimization"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("training_config", models.JSONField(default=dict)),
                ("progress", models.FloatField(default=0, help_text="Progress 0-100")),
                ("current_epoch", models.IntegerField(default=0)),
                ("total_epochs", models.IntegerField(default=100)),
                ("current_loss", models.FloatField(blank=True, null=True)),
                ("current_metric", models.FloatField(blank=True, null=True)),
                ("metrics_history", models.JSONField(default=list)),
                (
                    "final_metrics",
                    models.JSONField(default=dict, help_text="Final training metrics"),
                ),
                ("best_epoch", models.IntegerField(blank=True, null=True)),
                ("best_metric_value", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ml_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="tradingbot.mlmodel",
                    ),
                ),
                (
                    "rl_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="tradingbot.rlagent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignalSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "auto_replicate",
                    models.BooleanField(
                        default=False, help_text="Auto-execute trades from provider"
                    ),
                ),
                (
                    "max_allocation_pct",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("proportional_sizing", models.BooleanField(default=True)),
                (
                    "max_replication_delay_seconds",
                    models.PositiveIntegerField(default=300),
                ),
                ("notify_on_signal", models.BooleanField(default=True)),
                ("notify_on_entry", models.BooleanField(default=True)),
                ("notify_on_exit", models.BooleanField(default=True)),
                ("trades_replicated", models.PositiveIntegerField(default=0)),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="tradingbot.signalprovider",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("subscriber", "provider")},
            },
        ),
        migrations.CreateModel(
            name="ReplicatedTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_trade_id", models.CharField(max_length=100)),
                ("original_symbol", models.CharField(max_length=20)),
                ("original_side", models.CharField(max_length=10)),
                ("original_qty", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("original_timestamp", models.DateTimeField()),
                (
                    "replicated_qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "replicated_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("replicated_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "slippage_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "replication_delay_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            ("rejected_risk", "Rejected - Risk"),
                            ("rejected_delay", "Rejected - Delay"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replicated_trades",
                        to="tradingbot.signalsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this optimization run",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="User-defined name", max_length=200
                    ),
                ),
                (
                    "strategy_name",
                    models.CharField(
                        help_text="Strategy being optimized", max_length=100
                    ),
                ),
                ("start_date", models.DateField(help_text="Backtest period start")),
                ("end_date", models.DateField(help_text="Backtest period end")),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "loss_function",
                    models.CharField(
                        choices=[
                            ("sharpe", "Maximize Sharpe Ratio"),
                            ("sortino", "Maximize Sortino Ratio"),
                            ("calmar", "Maximize Calmar Ratio"),
                            ("return", "Maximize Total Return"),
                            ("profit_factor", "Maximize Profit Factor"),
                            ("win_rate", "Maximize Win Rate"),
                            ("min_drawdown", "Minimize Max Drawdown"),
                        ],
                        default="sharpe",
                        help_text="Metric to optimize",
                        max_length=50,
                    ),
                ),
                (
                    "n_trials",
                    models.IntegerField(
                        default=100, help_text="Number of optimization trials"
                    ),
                ),
                (
                    "sampler",
                    models.CharField(
                        choices=[
                            ("tpe", "TPE (Tree-structured Parzen Estimator)"),
                            ("random", "Random Search"),
                            ("cmaes", "CMA-ES"),
                            ("grid", "Grid Search"),
                        ],
                        default="tpe",
                        help_text="Optimization algorithm",
                        max_length=20,
                    ),
                ),
                (
                    "parameter_ranges",
                    models.JSONField(
                        default=dict, help_text="Parameter ranges for optimization"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="Progress 0-100"),
                ),
                (
                    "current_trial",
                    models.IntegerField(default=0, help_text="Current trial number"),
                ),
                (
                    "best_params",
                    models.JSONField(default=dict, help_text="Best parameters found"),
                ),
                (
                    "best_value",
                    models.FloatField(help_text="Best objective value", null=True),
                ),
                (
                    "best_sharpe",
                    models.FloatField(
                        help_text="Sharpe ratio with best params", null=True
                    ),
                ),
                (
                    "best_return_pct",
                    models.FloatField(help_text="Return with best params", null=True),
                ),
                (
                    "best_drawdown_pct",
                    models.FloatField(
                        help_text="Max drawdown with best params", null=True
                    ),
                ),
                (
                    "all_trials",
                    models.JSONField(
                        default=list,
                        help_text="All trial results [{params, value, metrics}]",
                    ),
                ),
                (
                    "parameter_importance",
                    models.JSONField(
                        default=dict, help_text="Parameter importance scores"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "custom_strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="optimization_runs",
                        to="tradingbot.customstrategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who ran this optimization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimization Run",
                "verbose_name_plural": "Optimization Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(
                        help_text="Trade identifier within the run", max_length=50
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, help_text="Traded symbol", max_length=20
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        help_text="Trade direction",
                        max_length=10,
                    ),
                ),
                ("entry_date", models.DateField(help_text="Entry date")),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=4, help_text="Entry price", max_digits=12
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Number of shares/contracts"),
                ),
                (
                    "exit_date",
                    models.DateField(blank=True, help_text="Exit date", null=True),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Exit price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("stopped_out", "Stopped Out"),
                            ("take_profit", "Take Profit"),
                            ("time_exit", "Time Exit"),
                        ],
                        default="open",
                        help_text="Trade status",
                        max_length=20,
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Profit/loss in dollars",
                        max_digits=12,
                    ),
                ),
                (
                    "pnl_pct",
                    models.FloatField(default=0, help_text="Profit/loss percentage"),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Commission paid",
                        max_digits=10,
                    ),
                ),
                (
                    "slippage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Slippage cost",
                        max_digits=10,
                    ),
                ),
                (
                    "entry_reason",
                    models.CharField(
                        blank=True,
                        help_text="Signal that triggered entry",
                        max_length=200,
                    ),
                ),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True, help_text="Reason for exit", max_length=200
                    ),
                ),
                (
                    "backtest_run",
                    models.ForeignKey(
                        help_text="Parent backtest run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="tradingbot.backtestrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backtest Trade",
                "verbose_name_plural": "Backtest Trades",
                "ordering": ["-entry_date"],
                "indexes": [
                    models.Index(
                        fields=["backtest_run", "symbol"],
                        name="tradingbot__backtes_875845_idx",
                    ),
                    models.Index(
                        fields=["backtest_run", "entry_date"],
                        name="tradingbot__backtes_0ea357_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["user", "strategy_name", "created_at"],
                name="tradingbot__user_id_ed8178_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["status", "created_at"], name="tradingbot__status_43242b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["user", "is_favorite"], name="tradingbot__user_id_b8dde2_idx"
            ),
        ),
    ]
