# Generated by Django 4.2.27 on 2026-02-21 05:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tradingbot", "0012_backtestrun_mlmodel_rlagent_signalprovider_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="alpaca_order_id",
            field=models.CharField(
                blank=True, default="", help_text="Alpaca order ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="filled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="filled_avg_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Filled average price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="limit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Limit price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("market", "Market"),
                    ("limit", "Limit"),
                    ("stop", "Stop"),
                    ("stop_limit", "Stop Limit"),
                    ("trailing_stop", "Trailing Stop"),
                ],
                default="market",
                help_text="Order type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stop_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stop price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="symbol",
            field=models.CharField(
                blank=True, default="", help_text="Trading symbol", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("new", "New"),
                    ("filled", "Filled"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Order status",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TradeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, help_text="Trading symbol", max_length=20
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        help_text="BUY or SELL transaction side",
                        max_length=4,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, help_text="Executed quantity", max_digits=18
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Executed or accepted price per unit",
                        max_digits=18,
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Absolute notional value (quantity * price)",
                        max_digits=24,
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Execution fees",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("new", "New"),
                            ("partially_filled", "Partially Filled"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="accepted",
                        help_text="Transaction lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Execution/acceptance timestamp",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="stock_trade_api",
                        help_text="Source subsystem that created the entry",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "legacy_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to legacy identifiers when available",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company traded",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tradingbot.company",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated order record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="tradingbot.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of the transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "executed_at"],
                        name="tradingbot__user_id_8e8aca_idx",
                    ),
                    models.Index(
                        fields=["company", "executed_at"],
                        name="tradingbot__company_f123b2_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "executed_at"],
                        name="tradingbot__transac_41faae_idx",
                    ),
                    models.Index(
                        fields=["status", "executed_at"],
                        name="tradingbot__status_c7f9b1_idx",
                    ),
                ],
            },
        ),
    ]
