"""
Financial Lexicon for Sentiment Analysis

VADER-style intensity scores for finance-specific terms.
Positive values indicate bullish sentiment; negative values indicate bearish.
The magnitude follows VADER conventions (roughly -4 to +4).
"""

from typing import Dict

FINANCIAL_LEXICON: Dict[str, float] = {
    # --- Strongly Bullish (+2.0 to +3.5) ---
    "bullish": 2.5,
    "upgrade": 2.5,
    "outperform": 2.5,
    "beat": 2.0,
    "beats": 2.0,
    "exceeded": 2.0,
    "exceeds": 2.0,
    "surge": 2.5,
    "surges": 2.5,
    "surging": 2.5,
    "rally": 2.5,
    "rallies": 2.5,
    "rallying": 2.5,
    "soar": 3.0,
    "soars": 3.0,
    "soaring": 3.0,
    "breakout": 2.5,
    "acquisition": 2.0,
    "buyback": 2.0,
    "dividend": 1.8,
    "growth": 2.0,
    "profit": 2.0,
    "profitable": 2.0,
    "revenue": 1.5,
    "record": 1.5,
    "upside": 2.0,
    "strong": 1.5,
    "momentum": 1.5,
    "overweight": 2.0,
    "buy": 2.0,
    "accumulate": 1.8,
    "innovation": 1.5,
    "expansion": 1.8,
    "boom": 2.5,
    "booming": 2.5,
    "recovery": 2.0,
    "rebound": 2.0,
    "rebounds": 2.0,
    "positive": 1.5,
    "optimistic": 2.0,
    "robust": 1.8,
    "catalyst": 1.5,
    "tailwind": 1.8,
    "outperformance": 2.5,
    "upbeat": 2.0,
    "blockbuster": 2.5,
    "moonshot": 3.0,
    "moon": 2.0,
    "rocket": 2.0,
    "tendies": 2.0,
    "squeeze": 1.5,
    "gamma": 1.0,

    # --- Mildly Bullish (+0.5 to +1.5) ---
    "steady": 0.8,
    "stable": 0.8,
    "hold": 0.5,
    "support": 1.0,
    "oversold": 1.0,

    # --- Mildly Bearish (-0.5 to -1.5) ---
    "resistance": -0.5,
    "overbought": -1.0,
    "sell": -1.5,
    "reduce": -1.0,
    "underweight": -1.5,
    "headwind": -1.5,
    "concern": -1.0,
    "concerns": -1.0,
    "caution": -1.0,
    "risk": -0.8,
    "risky": -1.0,
    "weak": -1.5,
    "weakness": -1.5,
    "slowdown": -1.5,
    "decline": -1.5,
    "declining": -1.5,
    "miss": -1.5,
    "misses": -1.5,
    "missed": -1.5,

    # --- Strongly Bearish (-2.0 to -3.5) ---
    "bearish": -2.5,
    "downgrade": -2.5,
    "underperform": -2.5,
    "plunge": -3.0,
    "plunges": -3.0,
    "plunging": -3.0,
    "crash": -3.0,
    "crashes": -3.0,
    "crashing": -3.0,
    "selloff": -2.5,
    "sell-off": -2.5,
    "tank": -2.5,
    "tanks": -2.5,
    "tanking": -2.5,
    "collapse": -3.0,
    "collapses": -3.0,
    "bankruptcy": -3.5,
    "bankrupt": -3.5,
    "recession": -3.0,
    "default": -3.0,
    "defaults": -3.0,
    "fraud": -3.5,
    "scandal": -3.0,
    "layoff": -2.0,
    "layoffs": -2.0,
    "lawsuit": -2.0,
    "investigation": -2.0,
    "subpoena": -2.5,
    "loss": -2.0,
    "losses": -2.0,
    "shortfall": -2.0,
    "warning": -2.0,
    "downside": -2.0,
    "overvalued": -2.0,
    "bubble": -2.5,
    "debt": -1.5,
    "leverage": -1.0,
    "dilution": -2.0,
    "bagholding": -2.0,
    "bagholder": -2.0,
    "rug": -3.0,
    "rugpull": -3.5,
    "dump": -2.5,
    "dumping": -2.5,

    # --- Volatility / Neutral-ish ---
    "volatile": -0.5,
    "volatility": -0.5,
    "uncertainty": -1.0,
    "inflation": -1.5,
    "deflation": -1.5,
    "stagflation": -2.5,
    "taper": -1.5,
    "tapering": -1.5,
    "hawkish": -1.0,
    "dovish": 1.0,
    "stimulus": 1.5,
    "easing": 1.5,
    "rate-cut": 1.5,
    "rate-hike": -1.5,
    "ipo": 1.0,
    "merger": 1.5,
    "restructuring": -1.0,
    "earnings": 0.5,
    "guidance": 0.5,
}
