name: Django CI

on:
  push:
    branches: [ main, "feature/*" ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: "secret_key"
      GITHUB_WORKFLOW: "true"
      DATABASE_URL: "postgres://postgres:password@127.0.0.1:5432/test"
      
    services:
      postgres:
        image: postgres:16.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # run flake8 with our configuration (setup.cfg)
          flake8 . --count --statistics
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      - name: Test Django setup
        run: python tests/integration/test_django_setup.py
      - name: Apply Migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test backend
